name: Build and Release Fonts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ GITHUB.SHA }}
          tag_name: release-${{ GITHUB.SHA }}
          files: |
            output_fonts/**/*.ttf
            output_fonts/**/*.otf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
